swagger: '2.0'
info:
  title: RBCL API
  description: Allows for interaction with RBCL data
  version: 0.2.0
#host: api.rbclouisville.com
basePath: /api/v1
schemes:
  - https
produces:
  - application/json
#x-google-backend:
#  address: https://family-api-6mu2ejwioa-ue.a.run.app
paths:
  /directory/families:
    get:
      summary: Get all family resources
      operationId: getFamilies
      x-google-backend:
        address: ${family_api_url}
      responses:
        '200':
          description: OK
          schema:
            type: string
  /directory/families/status:
    get:
      summary: Family API status check
      operationId: familiesStatus
      x-google-backend:
        address: ${family_api_url}/status
      responses:
        '200':
          description: OK
          schema:
            type: string
security:
  - auth0_jwk: []
securityDefinitions:
  auth0_jwk:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://${account_name}.auth0.com/"
    x-google-jwks_uri: "https://${account_name}.auth0.com/.well-known/jwks.json"
    x-google-audiences: "https://rbcl-api-gw-1ablkj45.ue.gateway.dev"