swagger: '2.0'
info:
  title: Family API
  description: Allows for interaction with RBCL family data
  version: 0.1.0
#host: api.rbclouisville.com
basePath: /api/v1
schemes:
  - https
produces:
  - application/json
#x-google-backend:
#  address: https://family-api-6mu2ejwioa-ue.a.run.app
paths:
  /families:
    get:
      summary: Get all family resources
      operationId: getFamilies
      x-google-backend:
        address: https://family-api-6mu2ejwioa-ue.a.run.app
      responses:
        '200':
          description: OK
          schema:
            type: string
  /families/status:
    get:
      summary: Cloud Run api status check
      operationId: familiesStatus
      x-google-backend:
        address: https://family-api-6mu2ejwioa-ue.a.run.app/status
      responses:
        '200':
          description: OK
          schema:
            type: string