# This is a basic workflow to help you get started with Actions

name: CHURCH-APP-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  family-api-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Gcloud Setup
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: rbc-louisville-project
        service_account_email: deploy@rbc-louisville-project.iam.gserviceaccount.com
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Setup Env
      run: |
        export TAG_TS=$(date +"%Y%m%d%H%M%S")
        echo "::set-env name=TAG_TS::$TAG_TS"
    
    - name: Run Build
      run: |
        TAG=$(cat .version)_$TAG_TS
        gcloud builds submit --tag gcr.io/rbc-louisville-project/family-api:$TAG
    - name: Deploy
      run: |
        TAG=$(cat .version)
        gcloud run deploy family-api --image gcr.io/rbc-louisville-project/family-api:$TAG